@echo off
echo Остановка всех процессов Node.js...
taskkill /f /im node.exe 2>nul
echo Ожидание освобождения портов...
timeout /t 5 /nobreak >nul
echo Проверка порта 3000...
netstat -an | findstr :3000
echo Запуск сервера...
npm run dev
